In [52]:
import pandas as pd
from geopy.distance import geodesic
from datetime import datetime
#import time

In [6]:
gps_data_df=pd.read_excel(r'./user_gps_data.xlsx',encoding='utf-16',index_col=0)
gps_data_df.head()

,user,time,latitude,longitude,elevation,speed,source,horizontal_dilution,vertical_dilution,course,satellites
0,user1,2019-11-26 16:44:00,25.052852,121.607082,42.199997,NaN,network,NaN,NaN,NaN,NaN
1,user1,2019-11-26 16:44:34,25.052853,121.607081,42.199997,NaN,network,NaN,NaN,NaN,NaN
2,user1,2019-11-26 16:45:46,25.052889,121.607220,35.699997,NaN,network,NaN,NaN,NaN,NaN
3,user1,2019-11-26 16:46:48,25.052797,121.607039,NaN,NaN,network,NaN,NaN,NaN,NaN
4,user1,2019-11-26 16:47:58,25.052446,121.607163,24.500000,NaN,network,NaN,NaN,NaN,NaN

# 求兩點距離及速度

In [69]:

#兩點距離求速度
localFormat = "%Y-%m-%d %H:%M:%S"
gps_data_df['point_speed']=0
gps_data_df['point_distance']=0
for user in list(set(gps_data_df['user'])):
    for i in gps_data_df[gps_data_df['user']==user].index:
        if i < gps_data_df[gps_data_df['user']==user].index[-1]:
            deltatime=datetime.strptime(gps_data_df.loc[i+1,'time'],localFormat)-datetime.strptime(gps_data_df.loc[i,'time'],localFormat)
            minutesdelta=(deltatime.seconds)/60
            if minutesdelta<10:
                prev=gps_data_df.loc[i,['latitude','longitude']]
                post=gps_data_df.loc[i+1,['latitude','longitude']]
                if minutesdelta>0:
                    gps_data_df.loc[i+1,'point_speed']=((geodesic(prev,post).kilometers)/minutesdelta)*60
                gps_data_df.loc[i+1,'point_distance']=(geodesic(prev,post).kilometers)
    #print(prev,post)

In [71]:
gps_data_df.to_excel(r'./gps_data_pointspeed.xlsx',encoding='utf-16')

In [27]:
gps_data_df[gps_data_df['user']==user].index

Int64Index([4884, 4885, 4886, 4887, 4888, 4889, 4890, 4891, 4892, 4893,
            ...
            9468, 9469, 9470, 9471, 9472, 9473, 9474, 9475, 9476, 9477],
           dtype='int64', length=4594)

In [64]:
localFormat = "%Y-%m-%d %H:%M:%S"
delta=datetime.strptime(gps_data_df.loc[i,'time'],localFormat)-datetime.strptime(gps_data_df.loc[i+1,'time'],localFormat)
print(delta.seconds)
#-gps_data_df.loc[i+1,'time']
#(geodesic(prev,post).kilometers)/

15504

# 求staypoint

In [72]:
#門檻值
#3km/hr 15mins
#1.5km/hr 15mins
gps_data_df_complete=pd.read_excel(r'./gps_data_pointspeed.xlsx',encoding='utf-16',index_col=0)
gps_data_df_complete.head()

,user,time,latitude,longitude,elevation,speed,source,horizontal_dilution,vertical_dilution,course,satellites,point_speed,point_distance
0,user1,2019-11-26 16:44:00,25.052852,121.607082,42.199997,NaN,network,NaN,NaN,NaN,NaN,0.000000,0.000000
1,user1,2019-11-26 16:44:34,25.052853,121.607081,42.199997,NaN,network,NaN,NaN,NaN,NaN,0.013911,0.000131
2,user1,2019-11-26 16:45:46,25.052889,121.607220,35.699997,NaN,network,NaN,NaN,NaN,NaN,0.730402,0.014608
3,user1,2019-11-26 16:46:48,25.052797,121.607039,NaN,NaN,network,NaN,NaN,NaN,NaN,1.216668,0.020954
4,user1,2019-11-26 16:47:58,25.052446,121.607163,24.500000,NaN,network,NaN,NaN,NaN,NaN,2.102851,0.040889

In [ ]:
speed_threshold=1.5
#if speed <1.5
#設定每個點停留時間
#加總每個點時間



    

gps_data_df_complete['stay_point_time']=0
localFormat = "%Y-%m-%d %H:%M:%S"
for user in list(set(gps_data_df['user'])):
    stay_point=[]
    for i in gps_data_df[gps_data_df['user']==user].index:
        if i < gps_data_df[gps_data_df['user']==user].index[-1]:
            stay_time=0
            if gps_data_df_complete.loc[i,'point_speed']<speed_threshold:
                deltatime=datetime.strptime(gps_data_df.loc[i+1,'time'],localFormat)-datetime.strptime(gps_data_df.loc[i,'time'],localFormat)
                minutesdelta=(deltatime.seconds)/60
                stay_time +=minutesdelta
            stay_point.append(gps_data_df_complete[i,'latitude'],gps_data_df_complete[i,'longitude'])
                

            if minutesdelta<10:
                prev=gps_data_df.loc[i,['latitude','longitude']]
                post=gps_data_df.loc[i+1,['latitude','longitude']]
                if minutesdelta>0:
                    gps_data_df.loc[i+1,'point_speed']=((geodesic(prev,post).kilometers)/minutesdelta)*60
                gps_data_df.loc[i+1,'point_distance']=(geodesic(prev,post).kilometers)