In [15]:
import re
import os
import pandas as pd
import xlsxwriter
import jieba

In [16]:
top=pd.read_json(r'C:/Users/Big data/PycharmProjects/ourETL/top.json')

In [44]:
card_l=[]
act_l=[]
for c in top['card']:
    for a in top['act']:
        if c not in card_l:
            card_l.append(c)
        if a not in act_l:
            act_l.append(a)
c_zero=[]
for i in range(len(card_l)):
    c_zero.append(0)
car_act=pd.DataFrame(columns=[card_l])
for i in act_l:
    car_act.loc[i]=c_zero
car_act=car_act.drop('',axis=0)
car_act=car_act.drop('',axis=1)

print(car_act)

for i in range(len(top)): 
    c=top['card'][i]
    a=top['act'][i]
    if a !='':
        if c !='':
            car_act.loc[a][c]+=1
        
print(car_act)
        
# table = pd.pivot_table(df, values='D', index=card_l,columns=act_l, aggfunc=np.sum, fill_value=0)

     Only Pi Flygo dawho 賴點 Linepay GOGO Ubear
紅利      0  0     0     0  0       0    0     0
旅遊      0  0     0     0  0       0    0     0
行動支付    0  0     0     0  0       0    0     0
加油      0  0     0     0  0       0    0     0
保險      0  0     0     0  0       0    0     0
電影      0  0     0     0  0       0    0     0
國外      0  0     0     0  0       0    0     0
網購      0  0     0     0  0       0    0     0
運動      0  0     0     0  0       0    0     0
     Only  Pi Flygo dawho 賴點 Linepay GOGO Ubear
紅利     17   7     0     3  2       1    3     0
旅遊      6  12     8     6  3       6    4     0
行動支付    1  27     0     2  2       2    6     2
加油      1   1     0     0  1       0    1     1
保險      0   0     0     2  1       0    1     0
電影      0   1     0     0  0       6    2     1
國外      0   3     2    17  9       1    9     0
網購      0  17     0     1  1       0    7     4
運動      1   0     0     0  0       0    0     0

In [45]:
car_act

     Only  Pi Flygo dawho 賴點 Linepay GOGO Ubear
紅利     17   7     0     3  2       1    3     0
旅遊      6  12     8     6  3       6    4     0
行動支付    1  27     0     2  2       2    6     2
加油      1   1     0     0  1       0    1     1
保險      0   0     0     2  1       0    1     0
電影      0   1     0     0  0       6    2     1
國外      0   3     2    17  9       1    9     0
網購      0  17     0     1  1       0    7     4
運動      1   0     0     0  0       0    0     0

In [49]:
top

         bank   card   act
0          玉山   Only    紅利
1          玉山     Pi    旅遊
10
100        國泰           旅遊
1000  Richart  Flygo    旅遊
1001       台新         行動支付
1002                    紅利
1003  Richart     Pi
1004                    加油
1005
1006                    旅遊
1007
1008                    旅遊
1009                    旅遊
101                     保險
1010                    旅遊
1011                    旅遊
1012
1013
1014       台新  dawho  行動支付
1015       台新           電影
1016       國泰
1017                    電影
1018       台新  Flygo    旅遊
1019                    旅遊
102        國泰           紅利
1020                    旅遊
1021                    旅遊
1022                    旅遊
1023       國泰           旅遊
...       ...    ...   ...
972                     旅遊
973                     網購
974        台新  Flygo    旅遊
975
976
977                     運動
978        中信           紅利
979                   行動支付
98         中信           紅利
980                     保險
981                   行動支付
982        台新         行動支付
983        兆豐
984                     網購
985                     旅遊
986
987        兆豐           旅遊
988        國泰
989        台新
99         台新           紅利
990
991                     旅遊
992        兆豐
993        台新           旅遊
994        玉山
995                     旅遊
996                     網購
997
998
999        台新  Flygo    旅遊

[2262 rows x 3 columns]

In [107]:
act_c=car_act.copy()
for i in car_act.index:
    k=car_act.loc[i]
    for num,j in enumerate(k):
        act_c.loc[i][num]=round(j/sum(k)*100,2)
act_c

       Only     Pi  Flygo  dawho     賴點 Linepay   GOGO  Ubear
紅利    51.52  21.21      0   9.09   6.06    3.03   9.09      0
旅遊    13.33  26.67  17.78  13.33   6.67   13.33   8.89      0
行動支付   2.38  64.29      0   4.76   4.76    4.76  14.29   4.76
加油       20     20      0      0     20       0     20     20
保險        0      0      0     50     25       0     25      0
電影        0     10      0      0      0      60     20     10
國外        0   7.32   4.88  41.46  21.95    2.44  21.95      0
網購        0  56.67      0   3.33   3.33       0  23.33  13.33
運動      100      0      0      0      0       0      0      0

In [ ]:
car_act

In [106]:
card_a=car_act.copy()
for i in car_act.head():
    k=car_act[i]
    for num,j in enumerate(k):
        card_a[i][num]=round(j/sum(k)*100,2)
card_a

       Only     Pi Flygo  dawho     賴點 Linepay   GOGO Ubear
紅利    65.38  10.29     0   9.68  10.53    6.25   9.09     0
旅遊    23.08  17.65    80  19.35  15.79    37.5  12.12     0
行動支付   3.85  39.71     0   6.45  10.53    12.5  18.18    25
加油     3.85   1.47     0      0   5.26       0   3.03  12.5
保險        0      0     0   6.45   5.26       0   3.03     0
電影        0   1.47     0      0      0    37.5   6.06  12.5
國外        0   4.41    20  54.84  47.37    6.25  27.27     0
網購        0     25     0   3.23   5.26       0  21.21    50
運動     3.85      0     0      0      0       0      0     0